apiVersion: v1
kind: Service
metadata:
  labels:
    app: pizza-menu
  name: pizza-menu-service
  namespace: pizza-menu
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: pizza-menu
  type: NodePort
